/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellPagosRouteImport } from './routes/_shell.pagos'
import { Route as ShellPadresRouteImport } from './routes/_shell.padres'
import { Route as ShellMensualidadesRouteImport } from './routes/_shell.mensualidades'
import { Route as ShellEstudiantesRouteImport } from './routes/_shell.estudiantes'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellCursosRouteImport } from './routes/_shell.cursos'
import { Route as ShellConceptosRouteImport } from './routes/_shell.conceptos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellPagosRoute = ShellPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPadresRoute = ShellPadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMensualidadesRoute = ShellMensualidadesRouteImport.update({
  id: '/mensualidades',
  path: '/mensualidades',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEstudiantesRoute = ShellEstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCursosRoute = ShellCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConceptosRoute = ShellConceptosRouteImport.update({
  id: '/conceptos',
  path: '/conceptos',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conceptos': typeof ShellConceptosRoute
  '/cursos': typeof ShellCursosRoute
  '/dashboard': typeof ShellDashboardRoute
  '/estudiantes': typeof ShellEstudiantesRoute
  '/mensualidades': typeof ShellMensualidadesRoute
  '/padres': typeof ShellPadresRoute
  '/pagos': typeof ShellPagosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conceptos': typeof ShellConceptosRoute
  '/cursos': typeof ShellCursosRoute
  '/dashboard': typeof ShellDashboardRoute
  '/estudiantes': typeof ShellEstudiantesRoute
  '/mensualidades': typeof ShellMensualidadesRoute
  '/padres': typeof ShellPadresRoute
  '/pagos': typeof ShellPagosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/conceptos': typeof ShellConceptosRoute
  '/_shell/cursos': typeof ShellCursosRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/estudiantes': typeof ShellEstudiantesRoute
  '/_shell/mensualidades': typeof ShellMensualidadesRoute
  '/_shell/padres': typeof ShellPadresRoute
  '/_shell/pagos': typeof ShellPagosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/conceptos'
    | '/cursos'
    | '/dashboard'
    | '/estudiantes'
    | '/mensualidades'
    | '/padres'
    | '/pagos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/conceptos'
    | '/cursos'
    | '/dashboard'
    | '/estudiantes'
    | '/mensualidades'
    | '/padres'
    | '/pagos'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/conceptos'
    | '/_shell/cursos'
    | '/_shell/dashboard'
    | '/_shell/estudiantes'
    | '/_shell/mensualidades'
    | '/_shell/padres'
    | '/_shell/pagos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/pagos': {
      id: '/_shell/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof ShellPagosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/padres': {
      id: '/_shell/padres'
      path: '/padres'
      fullPath: '/padres'
      preLoaderRoute: typeof ShellPadresRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mensualidades': {
      id: '/_shell/mensualidades'
      path: '/mensualidades'
      fullPath: '/mensualidades'
      preLoaderRoute: typeof ShellMensualidadesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/estudiantes': {
      id: '/_shell/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof ShellEstudiantesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cursos': {
      id: '/_shell/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof ShellCursosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/conceptos': {
      id: '/_shell/conceptos'
      path: '/conceptos'
      fullPath: '/conceptos'
      preLoaderRoute: typeof ShellConceptosRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellConceptosRoute: typeof ShellConceptosRoute
  ShellCursosRoute: typeof ShellCursosRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellEstudiantesRoute: typeof ShellEstudiantesRoute
  ShellMensualidadesRoute: typeof ShellMensualidadesRoute
  ShellPadresRoute: typeof ShellPadresRoute
  ShellPagosRoute: typeof ShellPagosRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellConceptosRoute: ShellConceptosRoute,
  ShellCursosRoute: ShellCursosRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellEstudiantesRoute: ShellEstudiantesRoute,
  ShellMensualidadesRoute: ShellMensualidadesRoute,
  ShellPadresRoute: ShellPadresRoute,
  ShellPagosRoute: ShellPagosRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
