/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellTransporteRouteImport } from './routes/_shell.transporte'
import { Route as ShellReportesRouteImport } from './routes/_shell.reportes'
import { Route as ShellPagosRouteImport } from './routes/_shell.pagos'
import { Route as ShellPadresRouteImport } from './routes/_shell.padres'
import { Route as ShellMorosidadRouteImport } from './routes/_shell.morosidad'
import { Route as ShellMensualidadesRouteImport } from './routes/_shell.mensualidades'
import { Route as ShellInscripcionesRouteImport } from './routes/_shell.inscripciones'
import { Route as ShellGastosRouteImport } from './routes/_shell.gastos'
import { Route as ShellEstudiantesRouteImport } from './routes/_shell.estudiantes'
import { Route as ShellDireccionRouteImport } from './routes/_shell.direccion'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellCursosRouteImport } from './routes/_shell.cursos'
import { Route as ShellConfiguracionRouteImport } from './routes/_shell.configuracion'
import { Route as ShellConceptosRouteImport } from './routes/_shell.conceptos'
import { Route as ShellComunicadosRouteImport } from './routes/_shell.comunicados'
import { Route as ShellCajaRouteImport } from './routes/_shell.caja'
import { Route as ShellAsistenciaRouteImport } from './routes/_shell.asistencia'
import { Route as ShellAcuerdosRouteImport } from './routes/_shell.acuerdos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellTransporteRoute = ShellTransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportesRoute = ShellReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPagosRoute = ShellPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPadresRoute = ShellPadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMorosidadRoute = ShellMorosidadRouteImport.update({
  id: '/morosidad',
  path: '/morosidad',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMensualidadesRoute = ShellMensualidadesRouteImport.update({
  id: '/mensualidades',
  path: '/mensualidades',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInscripcionesRoute = ShellInscripcionesRouteImport.update({
  id: '/inscripciones',
  path: '/inscripciones',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGastosRoute = ShellGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEstudiantesRoute = ShellEstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDireccionRoute = ShellDireccionRouteImport.update({
  id: '/direccion',
  path: '/direccion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCursosRoute = ShellCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfiguracionRoute = ShellConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConceptosRoute = ShellConceptosRouteImport.update({
  id: '/conceptos',
  path: '/conceptos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComunicadosRoute = ShellComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCajaRoute = ShellCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAsistenciaRoute = ShellAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAcuerdosRoute = ShellAcuerdosRouteImport.update({
  id: '/acuerdos',
  path: '/acuerdos',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/acuerdos': typeof ShellAcuerdosRoute
  '/asistencia': typeof ShellAsistenciaRoute
  '/caja': typeof ShellCajaRoute
  '/comunicados': typeof ShellComunicadosRoute
  '/conceptos': typeof ShellConceptosRoute
  '/configuracion': typeof ShellConfiguracionRoute
  '/cursos': typeof ShellCursosRoute
  '/dashboard': typeof ShellDashboardRoute
  '/direccion': typeof ShellDireccionRoute
  '/estudiantes': typeof ShellEstudiantesRoute
  '/gastos': typeof ShellGastosRoute
  '/inscripciones': typeof ShellInscripcionesRoute
  '/mensualidades': typeof ShellMensualidadesRoute
  '/morosidad': typeof ShellMorosidadRoute
  '/padres': typeof ShellPadresRoute
  '/pagos': typeof ShellPagosRoute
  '/reportes': typeof ShellReportesRoute
  '/transporte': typeof ShellTransporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/acuerdos': typeof ShellAcuerdosRoute
  '/asistencia': typeof ShellAsistenciaRoute
  '/caja': typeof ShellCajaRoute
  '/comunicados': typeof ShellComunicadosRoute
  '/conceptos': typeof ShellConceptosRoute
  '/configuracion': typeof ShellConfiguracionRoute
  '/cursos': typeof ShellCursosRoute
  '/dashboard': typeof ShellDashboardRoute
  '/direccion': typeof ShellDireccionRoute
  '/estudiantes': typeof ShellEstudiantesRoute
  '/gastos': typeof ShellGastosRoute
  '/inscripciones': typeof ShellInscripcionesRoute
  '/mensualidades': typeof ShellMensualidadesRoute
  '/morosidad': typeof ShellMorosidadRoute
  '/padres': typeof ShellPadresRoute
  '/pagos': typeof ShellPagosRoute
  '/reportes': typeof ShellReportesRoute
  '/transporte': typeof ShellTransporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/acuerdos': typeof ShellAcuerdosRoute
  '/_shell/asistencia': typeof ShellAsistenciaRoute
  '/_shell/caja': typeof ShellCajaRoute
  '/_shell/comunicados': typeof ShellComunicadosRoute
  '/_shell/conceptos': typeof ShellConceptosRoute
  '/_shell/configuracion': typeof ShellConfiguracionRoute
  '/_shell/cursos': typeof ShellCursosRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/direccion': typeof ShellDireccionRoute
  '/_shell/estudiantes': typeof ShellEstudiantesRoute
  '/_shell/gastos': typeof ShellGastosRoute
  '/_shell/inscripciones': typeof ShellInscripcionesRoute
  '/_shell/mensualidades': typeof ShellMensualidadesRoute
  '/_shell/morosidad': typeof ShellMorosidadRoute
  '/_shell/padres': typeof ShellPadresRoute
  '/_shell/pagos': typeof ShellPagosRoute
  '/_shell/reportes': typeof ShellReportesRoute
  '/_shell/transporte': typeof ShellTransporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/acuerdos'
    | '/asistencia'
    | '/caja'
    | '/comunicados'
    | '/conceptos'
    | '/configuracion'
    | '/cursos'
    | '/dashboard'
    | '/direccion'
    | '/estudiantes'
    | '/gastos'
    | '/inscripciones'
    | '/mensualidades'
    | '/morosidad'
    | '/padres'
    | '/pagos'
    | '/reportes'
    | '/transporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/acuerdos'
    | '/asistencia'
    | '/caja'
    | '/comunicados'
    | '/conceptos'
    | '/configuracion'
    | '/cursos'
    | '/dashboard'
    | '/direccion'
    | '/estudiantes'
    | '/gastos'
    | '/inscripciones'
    | '/mensualidades'
    | '/morosidad'
    | '/padres'
    | '/pagos'
    | '/reportes'
    | '/transporte'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/acuerdos'
    | '/_shell/asistencia'
    | '/_shell/caja'
    | '/_shell/comunicados'
    | '/_shell/conceptos'
    | '/_shell/configuracion'
    | '/_shell/cursos'
    | '/_shell/dashboard'
    | '/_shell/direccion'
    | '/_shell/estudiantes'
    | '/_shell/gastos'
    | '/_shell/inscripciones'
    | '/_shell/mensualidades'
    | '/_shell/morosidad'
    | '/_shell/padres'
    | '/_shell/pagos'
    | '/_shell/reportes'
    | '/_shell/transporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/transporte': {
      id: '/_shell/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof ShellTransporteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reportes': {
      id: '/_shell/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ShellReportesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pagos': {
      id: '/_shell/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof ShellPagosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/padres': {
      id: '/_shell/padres'
      path: '/padres'
      fullPath: '/padres'
      preLoaderRoute: typeof ShellPadresRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/morosidad': {
      id: '/_shell/morosidad'
      path: '/morosidad'
      fullPath: '/morosidad'
      preLoaderRoute: typeof ShellMorosidadRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mensualidades': {
      id: '/_shell/mensualidades'
      path: '/mensualidades'
      fullPath: '/mensualidades'
      preLoaderRoute: typeof ShellMensualidadesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inscripciones': {
      id: '/_shell/inscripciones'
      path: '/inscripciones'
      fullPath: '/inscripciones'
      preLoaderRoute: typeof ShellInscripcionesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/gastos': {
      id: '/_shell/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof ShellGastosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/estudiantes': {
      id: '/_shell/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof ShellEstudiantesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/direccion': {
      id: '/_shell/direccion'
      path: '/direccion'
      fullPath: '/direccion'
      preLoaderRoute: typeof ShellDireccionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cursos': {
      id: '/_shell/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof ShellCursosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/configuracion': {
      id: '/_shell/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ShellConfiguracionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/conceptos': {
      id: '/_shell/conceptos'
      path: '/conceptos'
      fullPath: '/conceptos'
      preLoaderRoute: typeof ShellConceptosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/comunicados': {
      id: '/_shell/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ShellComunicadosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/caja': {
      id: '/_shell/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof ShellCajaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/asistencia': {
      id: '/_shell/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof ShellAsistenciaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/acuerdos': {
      id: '/_shell/acuerdos'
      path: '/acuerdos'
      fullPath: '/acuerdos'
      preLoaderRoute: typeof ShellAcuerdosRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAcuerdosRoute: typeof ShellAcuerdosRoute
  ShellAsistenciaRoute: typeof ShellAsistenciaRoute
  ShellCajaRoute: typeof ShellCajaRoute
  ShellComunicadosRoute: typeof ShellComunicadosRoute
  ShellConceptosRoute: typeof ShellConceptosRoute
  ShellConfiguracionRoute: typeof ShellConfiguracionRoute
  ShellCursosRoute: typeof ShellCursosRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDireccionRoute: typeof ShellDireccionRoute
  ShellEstudiantesRoute: typeof ShellEstudiantesRoute
  ShellGastosRoute: typeof ShellGastosRoute
  ShellInscripcionesRoute: typeof ShellInscripcionesRoute
  ShellMensualidadesRoute: typeof ShellMensualidadesRoute
  ShellMorosidadRoute: typeof ShellMorosidadRoute
  ShellPadresRoute: typeof ShellPadresRoute
  ShellPagosRoute: typeof ShellPagosRoute
  ShellReportesRoute: typeof ShellReportesRoute
  ShellTransporteRoute: typeof ShellTransporteRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAcuerdosRoute: ShellAcuerdosRoute,
  ShellAsistenciaRoute: ShellAsistenciaRoute,
  ShellCajaRoute: ShellCajaRoute,
  ShellComunicadosRoute: ShellComunicadosRoute,
  ShellConceptosRoute: ShellConceptosRoute,
  ShellConfiguracionRoute: ShellConfiguracionRoute,
  ShellCursosRoute: ShellCursosRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDireccionRoute: ShellDireccionRoute,
  ShellEstudiantesRoute: ShellEstudiantesRoute,
  ShellGastosRoute: ShellGastosRoute,
  ShellInscripcionesRoute: ShellInscripcionesRoute,
  ShellMensualidadesRoute: ShellMensualidadesRoute,
  ShellMorosidadRoute: ShellMorosidadRoute,
  ShellPadresRoute: ShellPadresRoute,
  ShellPagosRoute: ShellPagosRoute,
  ShellReportesRoute: ShellReportesRoute,
  ShellTransporteRoute: ShellTransporteRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
